---
# Bibliotecas

In [28]:
import matplotlib
import matplotlib.pyplot as plt
import matplotlib.image as mpimg
import pandas as pd
import numpy as np
import sentence_transformers
from sentence_transformers import SentenceTransformer
import tensorflow as tf
import torch

---
![sdfsdf](https://raw.githubusercontent.com/marcusvbrangel/ia-base-expert/main/cursos/algebra-linear/imagens/tabela-escalares-vetores-matrizes-tensores.jpeg)

---
# Escalares

In [29]:
# positivo
3

3

In [30]:
# negativo
-2

-2

In [31]:
# divisao
5/7

0.7142857142857143

In [32]:
# expoente
7**2

49

In [33]:
# raiz
5**(1/2)  

2.23606797749979

In [45]:
# numero 8 no formato da biblioteca numpy
scalar = np.array(8)
print(scalar, flush=True)             # valor:     8
print(type(scalar), flush=True)       # tipo:      <class 'numpy.ndarray'>
print(scalar.ndim, flush=True)        # dimensao:  0

8
<class 'numpy.ndarray'>
0


---
# Vetores

In [46]:
lista = [1, 2, 3]
print(lista)

[1, 2, 3]


In [49]:
type(lista)

list

In [51]:
# OBSERVAÇÃO: nao podemos fazer calculos vetoriais em cima desta variavel lista
# por exemplo ao multiplicar a lista por dois o valor resultante é uma concatenacao -> [1, 2, 3, 1, 2, 3]
lista * 2

[1, 2, 3, 1, 2, 3]

In [52]:
# OBSERVAÇÃO: daqui para frente vamos usar o numpy para criar vetores, pois aceitam calculos vetoriais
vector = np.array([1, 2, 3])

In [53]:
print(vector)

[1 2 3]


In [54]:
type(vector)

numpy.ndarray

In [55]:
vector.ndim

1

In [56]:
# agora podemos fazer a operação matematica
vector * 2

array([2, 4, 6])

---
# Matrizes

In [58]:
# criação de matriz na notacao de linha a linha
matrix = np.array(
    [
        [1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]
    ]
)

In [59]:
print(matrix)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [60]:
type(matrix)

numpy.ndarray

In [66]:
matrix.ndim

# representação: linha coluna -> a m -> i j
# a11   a12   ...   a1n
# a21   a22   ...   a2n
#  .     .    ...    .
#  .     .    ...    .
# am1   am2   ...   amn

2

In [70]:
# retornando linhas
matrix[0]

array([1, 2, 3])

In [68]:
matrix[1]

array([4, 5, 6])

In [69]:
matrix[2]

array([7, 8, 9])

In [74]:
# retornando colunas
matrix[:, 0]

array([1, 4, 7])

In [75]:
matrix[:, 1]

array([2, 5, 8])

In [76]:
matrix[:, 2]

array([3, 6, 9])

In [77]:
# retornando apenas um valor (uma posição)
matrix[2][0]

np.int64(7)

In [78]:
# multiplicação
matrix * 2

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

---
# Tensores

In [80]:
# notação de listas de listas de listas
tensor_np = np.array(
    [
        [
            [1, 2, 3],
            [4, 5, 6]
        ],
        [
            [7, 8, 9],
            [10, 11, 12]  # listas internas
        ]  
    ]  # lista intermediaria
)  # lista externa

In [81]:
print(tensor_np)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [82]:
type(tensor_np)

numpy.ndarray

In [83]:
tensor_np.ndim

3